name: bg-agent
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.5
  - pip
  - pip:
      - torch==2.2.2
      - numpy==1.26.4
      - hearthstone==9.20.0
      - hslog==1.18.0
      - requests==2.32.5
      - tqdm==4.62.3
      - rich==15.0.0
      - matplotlib==3.7.5
      - ipykernel==6.29.5
